"""m1_initial_schema

Revision ID: 4591ef6c363b
Revises: 
Create Date: 2026-09-20 16:16:06.874340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4591ef6c363b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('wa_phone', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('consent_state', sa.String(length=20), nullable=False),
    sa.Column('disclosure_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disclosure_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wa_phone', name='uq_member_wa_phone')
    )
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wa_message_id', sa.String(length=128), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('wa_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wa_message_id', name='uq_message_wa_message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('member')
    op.drop_table('household')
    # ### end Alembic commands ###
